"""empty message

Revision ID: 832f75768cb6
Revises: 
Create Date: 2019-11-16 21:45:06.835753

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '832f75768cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('picture_caption_2', table_name='picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('picture_caption_2', 'picture', ['picture_caption', 'picture_link'], unique=False)
    # ### end Alembic commands ###
